package magazinestore.entity;
// Generated 27-apr-2019 19.55.30 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DettagliOrdineId generated by hbm2java
 */
@Embeddable
public class DettagliOrdineId implements java.io.Serializable {

	private Integer ordineId;
	private Integer revistaId;
	private int quantity;
	private float subtotal;

	public DettagliOrdineId() {
	}

	public DettagliOrdineId(int quantity, float subtotal) {
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public DettagliOrdineId(Integer ordineId, Integer revistaId, int quantity, float subtotal) {
		this.ordineId = ordineId;
		this.revistaId = revistaId;
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	@Column(name = "ordine_id")
	public Integer getOrdineId() {
		return this.ordineId;
	}

	public void setOrdineId(Integer ordineId) {
		this.ordineId = ordineId;
	}

	@Column(name = "revista_id")
	public Integer getRevistaId() {
		return this.revistaId;
	}

	public void setRevistaId(Integer revistaId) {
		this.revistaId = revistaId;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	public float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DettagliOrdineId))
			return false;
		DettagliOrdineId castOther = (DettagliOrdineId) other;

		return ((this.getOrdineId() == castOther.getOrdineId()) || (this.getOrdineId() != null
				&& castOther.getOrdineId() != null && this.getOrdineId().equals(castOther.getOrdineId())))
				&& ((this.getRevistaId() == castOther.getRevistaId()) || (this.getRevistaId() != null
						&& castOther.getRevistaId() != null && this.getRevistaId().equals(castOther.getRevistaId())))
				&& (this.getQuantity() == castOther.getQuantity()) && (this.getSubtotal() == castOther.getSubtotal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrdineId() == null ? 0 : this.getOrdineId().hashCode());
		result = 37 * result + (getRevistaId() == null ? 0 : this.getRevistaId().hashCode());
		result = 37 * result + this.getQuantity();
		result = 37 * result + (int) this.getSubtotal();
		return result;
	}

}
