package magazinestore.entity;
// Generated 27-apr-2019 19.55.30 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DettagliOrdine generated by hbm2java
 */
@Entity
@Table(name = "dettagli_ordine", catalog = "magazinestoredb")
public class DettagliOrdine implements java.io.Serializable {

	private DettagliOrdineId id;
	private OrdineRevista ordineRevista;
	private Rivista rivista;

	public DettagliOrdine() {
	}

	public DettagliOrdine(DettagliOrdineId id) {
		this.id = id;
	}

	public DettagliOrdine(DettagliOrdineId id, OrdineRevista ordineRevista, Rivista rivista) {
		this.id = id;
		this.ordineRevista = ordineRevista;
		this.rivista = rivista;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ordineId", column = @Column(name = "ordine_id")),
			@AttributeOverride(name = "revistaId", column = @Column(name = "revista_id")),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", nullable = false)),
			@AttributeOverride(name = "subtotal", column = @Column(name = "subtotal", nullable = false, precision = 12, scale = 0)) })
	public DettagliOrdineId getId() {
		return this.id;
	}

	public void setId(DettagliOrdineId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordine_id", insertable = false, updatable = false)
	public OrdineRevista getOrdineRevista() {
		return this.ordineRevista;
	}

	public void setOrdineRevista(OrdineRevista ordineRevista) {
		this.ordineRevista = ordineRevista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "revista_id", insertable = false, updatable = false)
	public Rivista getRivista() {
		return this.rivista;
	}

	public void setRivista(Rivista rivista) {
		this.rivista = rivista;
	}

}
